now doing full build

diff --git a/.github/workflows/local-ci.yaml b/.github/workflows/local-ci.yaml
--- a/.github/workflows/local-ci.yaml
+++ b/.github/workflows/local-ci.yaml
@@ -40,13 +40,13 @@ jobs:
 
       - name: Build, Test
         run: |
-          cargo build -p reth-provider --locked
+          cargo build  --locked
           
-      - name: Format and commit
-        run: |	
-          rustfmt --edition 2024 crates/storage/provider/src/providers/rocksdb/provider.rs
-          git config user.email "actions@github.com"
-          git config user.name "Github Actions"
-          git add .
-          git commit -m "CI: comming formatting changes [skip ci]" || echo "Nothing to commit"
-          git push || echo "Push failed"
+#      - name: Format and commit
+#        run: |	
+#          rustfmt --edition 2024 crates/storage/provider/src/providers/rocksdb/provider.rs
+#          git config user.email "actions@github.com"
+#          git config user.name "Github Actions"
+#          git add .
+#          git commit -m "CI: comming formatting changes [skip ci]" || echo "Nothing to commit"
+#          git push || echo "Push failed"
